In [102]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, __у кого__ списали) не могут получить за него больше 0 баллов.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу курса XXX выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [103]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [104]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [105]:
# Записать ответ в переменную num_studs
num_studs = marks.shape[0]

In [106]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [107]:
# Записать ответ в переменную max_mark
max_mark = np.max(marks, axis=0)[0]

In [108]:
print(max_mark)

7.0


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [109]:
marks[:,0] = marks[:,0]*10/max_mark

In [110]:
print(marks)

[[10.          8.         10.          0.          0.          2.1
   1.5       ]
 [ 0.          6.          4.4         4.          0.          5.
   4.3       ]
 [ 4.28571429  7.          8.7         7.6         7.          9.7
  10.        ]
 [ 4.85714286  1.3         7.          3.4         0.          9.4
   9.        ]
 [ 9.71428571  9.1         8.2         0.          0.          7.9
   7.9       ]
 [10.         10.         10.          9.          9.5        10.
   8.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7       ]
 [ 0.          9.3         5.7         0.          0.          0.
   0.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.        ]
 [ 0.          8.7         8.          9.7        10.          9.5
  10.        ]
 [ 4.28571429  6.9         7.9         0.          0.          0.
   0.        ]
 [ 5.71428571 10.         10.          9.9         9.7        10.
   9.        ]
 [ 0.          0.     

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [111]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = [0.3, 0.4, 0.3]

In [112]:
quizzes_av = np.mean(marks[:,:3], axis=1).reshape(28,1)
print(quizzes_av)

[[ 9.33333333]
 [ 3.46666667]
 [ 6.66190476]
 [ 4.38571429]
 [ 9.0047619 ]
 [10.        ]
 [ 9.42380952]
 [ 5.        ]
 [ 9.04761905]
 [ 5.56666667]
 [ 6.36190476]
 [ 8.57142857]
 [ 0.        ]
 [ 7.85714286]
 [ 8.71428571]
 [ 4.46666667]
 [10.        ]
 [ 8.37619048]
 [ 0.        ]
 [ 4.76666667]
 [ 0.        ]
 [ 9.52380952]
 [ 9.16190476]
 [ 9.9       ]
 [ 5.93333333]
 [ 8.8       ]
 [ 7.66190476]
 [ 8.1       ]]


In [113]:
hw_av=np.mean(marks[:,3:6], axis=1)
hw_av = hw_av.reshape(28,1)
print(hw_av)

[[ 0.7       ]
 [ 3.        ]
 [ 8.1       ]
 [ 4.26666667]
 [ 2.63333333]
 [ 9.5       ]
 [ 8.06666667]
 [ 0.        ]
 [10.13333333]
 [ 9.73333333]
 [ 0.        ]
 [ 9.86666667]
 [ 0.        ]
 [ 9.9       ]
 [ 8.3       ]
 [ 0.        ]
 [ 9.9       ]
 [ 3.16666667]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 8.9       ]
 [10.1       ]
 [ 9.36666667]
 [ 3.16666667]
 [ 5.5       ]
 [10.03333333]
 [ 9.96666667]]


In [114]:
cumul = quizzes_av * weights[0] + hw_av * weights[1] + marks[:,6:7]*weights[2]
marks = np.hstack((marks, cumul.reshape(-1,1)))
print(marks)

[[10.          8.         10.          0.          0.          2.1
   1.5         3.53      ]
 [ 0.          6.          4.4         4.          0.          5.
   4.3         3.53      ]
 [ 4.28571429  7.          8.7         7.6         7.          9.7
  10.          8.23857143]
 [ 4.85714286  1.3         7.          3.4         0.          9.4
   9.          5.72238095]
 [ 9.71428571  9.1         8.2         0.          0.          7.9
   7.9         6.1247619 ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2       ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952]
 [ 0.          9.3         5.7         0.          0.          0.
   0.          1.5       ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905]
 [ 0.          8.7         8.          9.7        10.          9.5
  10.          8.56333333]
 [ 4.28571429  6.9         7.9         0.          0.          0

### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [115]:
np.sum([True, False, True]) # 2 значения True

2

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [116]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


In [117]:
np.sum(cumul == 0)

3

### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [118]:
auto = np.sum(cumul > 7, axis=1)
auto.reshape(-1,1)
print(auto)

[0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 1]


In [119]:
marks = np.hstack((marks, auto.reshape(-1,1)))
print(marks)

[[10.          8.         10.          0.          0.          2.1
   1.5         3.53        0.        ]
 [ 0.          6.          4.4         4.          0.          5.
   4.3         3.53        0.        ]
 [ 4.28571429  7.          8.7         7.6         7.          9.7
  10.          8.23857143  1.        ]
 [ 4.85714286  1.3         7.          3.4         0.          9.4
   9.          5.72238095  0.        ]
 [ 9.71428571  9.1         8.2         0.          0.          7.9
   7.9         6.1247619   0.        ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2         1.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952  1.        ]
 [ 0.          9.3         5.7         0.          0.          0.
   0.          1.5         0.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905  1.        ]
 [ 0.          8.7         8.          9.7        

### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.sort) и взять первую половину.

In [120]:
top_cumul = marks[:,-2].argsort()[::-1]


In [121]:
free = marks[top_cumul]
free = free[:len(free)//2, :]
print(free)

[[10.         10.         10.          9.7        10.         10.
  10.          9.96        1.        ]
 [ 9.28571429  8.7         9.5        10.5         9.8        10.
  10.          9.78857143  1.        ]
 [10.          9.7        10.          8.1        10.         10.
   9.5         9.56666667  1.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905  1.        ]
 [ 5.71428571 10.         10.          9.9         9.7        10.
   9.          9.21809524  1.        ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2         1.        ]
 [ 4.28571429  8.7        10.          9.4        10.7        10.
   9.          9.01190476  1.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952  1.        ]
 [ 5.          9.3        10.          9.9        10.         10.
   8.          8.81666667  1.        ]
 [ 8.57142857  5.         10.          9.7        10. 

### Сложность заданий (1.5 балла)
Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами.
Пример, что имеется в виду: если есть 4 студента с весами [0.1, 0.2, 0.3, 0.4] и оценками [3, 7, 9, 10], то средняя оценка за задание с весами получится 

In [122]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [123]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))
# разделите веса на их сумму, чтобы они суммировались к 1
weights = np.array([weights/np.sum(weights)])
print(weights)

[[0.01315789 0.01315789 0.01315789 0.01315789 0.01315789 0.01315789
  0.01315789 0.02631579 0.02631579 0.02631579 0.02631579 0.03947368
  0.03947368 0.03947368 0.03947368 0.03947368 0.03947368 0.03947368
  0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158
  0.05263158 0.05263158 0.05263158 0.05263158]]


Посчитайте указанным образом сложность каждого "столбца".

In [124]:
avs = np.array([np.dot(weights, np.array(marks[:,0]))]+ [np.dot(weights, np.array(marks[:,1]))] + [np.dot(weights, np.array(marks[:,2]))] + [np.dot(weights, np.array(marks[:,3]))] + [np.dot(weights, np.array(marks[:,4]))] + [np.dot(weights, np.array(marks[:,5]))] + [np.dot(weights, np.array(marks[:,6]))])

In [125]:
print(avs)

[[4.90037594]
 [7.11973684]
 [7.85789474]
 [6.16447368]
 [4.83289474]
 [5.87894737]
 [4.87368421]]
